# config file to create surface property files from COSMO data to perform PV forward model calibration

# path where COSMO netCDF data files are located
path_cosmo: MetPVNet/Code/COSMO/raw_data/

# list of COSMO filenames or else from_dates
fnames_cosmo: [cosmo_d2_20180912.nc,cosmo_d2_20180917.nc,cosmo_d2_20180920.nc, 
            cosmo_d2_20180927.nc,cosmo_d2_20180930.nc,cosmo_d2_20181004.nc,
            cosmo_d2_20181005.nc,cosmo_d2_20181008.nc,cosmo_d2_20181010.nc,
            cosmo_d2_20181012.nc,cosmo_d2_20181013.nc,cosmo_d2_20181014.nc]

#Can be a list of dates in YYYY-MM-DD format or else a list of lists with start and end dates for range
dates: [2018-09-12,2018-09-17]

# path where the surface files will be saved
path_surface_files: MetPVNet/Code/COSMO/pvcal_input_cosmo

# names of COSMO variables and dimensions
variable_names_cosmo:
    Zonal wind: 10u #U_10M
    Meridional wind: 10v #V_10M
    
    Temperature_sfc: 2t #T_2M
    
    time: time
    lat: lat
    lon: lon
    
    level_alt: HHL

    pollat: [rotated_pole,grid_north_pole_latitude]
    pollon: [rotated_pole,grid_north_pole_longitude]

# timeresolution in minutes, if None: timeresolution equal to resolution of COSMO data
timeresolution: 15.

# latitude, longitude of locations (position of solar power plants) within the COSMO grid
stations_lat_lon:
    MS_01: [47.715877,10.314037]
    MS_02: [47.683233,10.319028]
    PV_04: [47.76683,10.40843]
    PV_11: [47.653161,10.496584]
    PV_12: [47.640997,10.387674]
    PV_15: [47.61811,10.49656]   
    PV_03: [47.76754,10.39832]
