# config file to create surface property files from COSMO data to perform PV forward model calibration

# path where COSMO netCDF data files are located
path_cosmo: MetPVNet/Data/COSMO/raw_data/cosmo_kampagne_2018_all_new

# list of COSMO filenames
#fnames_cosmo: [cosmo_d2_20180912.nc,cosmo_d2_20180917.nc,cosmo_d2_20180920.nc, 
#            cosmo_d2_20180927.nc,cosmo_d2_20180930.nc,cosmo_d2_20181004.nc,
#            cosmo_d2_20181005.nc,cosmo_d2_20181008.nc,cosmo_d2_20181010.nc,
#            cosmo_d2_20181012.nc,cosmo_d2_20181013.nc,cosmo_d2_20181014.nc]
            
# list of COSMO filenames
fnames_cosmo: from_dates

#List of dates or nested list with daterange
dates: [[2018-09-05,2018-10-15]]            

# path where the surface files will be saved
path_surface_files: MetPVNet/Data/COSMO/pvcal_input_cosmo

# path where the irradiance files will be saved
path_irradiance_files: MetPVNet/Data/COSMO/irradiance_output

# names of COSMO variables and dimensions
variable_names_cosmo:
    Zonal wind: 10u #U_10M
    Meridional wind: 10v #V_10M
    
    Temperature_sfc: 2t #T_2M
    
    time: time
    lat: lat
    lon: lon
    
    level_alt: HHL

    pollat: [rotated_pole,grid_north_pole_latitude]
    pollon: [rotated_pole,grid_north_pole_longitude]
    
    irrad_direct: SWDIR_S
    irrad_diffuse: SWDIFD_S
    
    cloud_mixrat: clwmr

# timeresolution in minutes, if None: timeresolution equal to resolution of COSMO data
timeresolution: 15.

# reduce vertical resoloution to achieve better performance of Mystic
reduce_vertical_resoloution: False

# modify Ozone concentration in Atmosphere file. use False if you dont want to change anything,
# provide the desired Ozone column in Dobson units (DU) if you want to change the concentration
modify_ozone: False 

#Number of grid boxes in each direction to average over, i.e. lat - x , lat + x, lon - y, lon + y  
#This will only be applied to irradiance data in order to calculate an error bar
grid_avg:
    lat: 2
    lon: 2

# latitude, longitude of locations (position of solar power plants) within the COSMO grid
stations_lat_lon:
    MS_01: [47.715877,10.314037]
    MS_02: [47.683233,10.319028]
    PV_04: [47.76683,10.40843]
    PV_11: [47.653161,10.496584]
    PV_12: [47.640997,10.387674]
    PV_15: [47.61811,10.49656]   
    PV_03: [47.76754,10.39832]
    PV_06: [47.75014,10.31668]
    PV_16: [47.61035,10.22710]
    PV_20: [47.54129,10.43964]
    PV_21: [47.53019,10.25957]
    PV_01: [47.79314,10.41914]
    PV_07: [47.74298,10.23326]
    PV_13: [47.64058,10.24982]
    PV_18: [47.58829,10.23160]
    PV_08: [47.71985,10.23064]
    PV_17: [47.59261,10.09873]
    PV_09: [47.71785,10.31660]
    PV_14: [47.63978,10.11741]
    PV_22: [47.46471,10.26521]
    PV_10: [47.66487,10.11355]
    PV_19: [47.54270,10.44595]
    PV_02: [47.76869,10.40038]
    PV_05: [47.76352,10.40331]
