# config file to extract cloud properties surface property files from COSMO data to perform PV forward model calibration

#Config for APOLLO data
path_apollo: MetPVNet/Data/SEVIRI/raw_data_apollo/2019

# path where COSMO netCDF data files are located
path_seviri: MetPVNet/Data/SEVIRI/raw_data_hrv

# list of COSMO filenames
#fnames_cosmo: [cosmo_d2_20180912.nc,cosmo_d2_20180917.nc,cosmo_d2_20180920.nc, 
#            cosmo_d2_20180927.nc,cosmo_d2_20180930.nc,cosmo_d2_20181004.nc,
#            cosmo_d2_20181005.nc,cosmo_d2_20181008.nc,cosmo_d2_20181010.nc,
#            cosmo_d2_20181012.nc,cosmo_d2_20181013.nc,cosmo_d2_20181014.nc]
            
# list of COSMO foldernames
fnames_seviri: from_dates

#List of dates or nested list with daterange
dates: [2019-07-15,2019-07-19,2019-07-21,2019-07-28,2019-07-31]            

# path where the surface files will be saved
path_cod_files: MetPVNet/Data/SEVIRI/cod_output

#File with geographic coordinates
coord_file: geoloc.nc

# names of COSMO variables and dimensions
variable_names_seviri:
    cod: cot
    d_cod: cot_unc
    
    time: time
    coords:
        lat: lat
        lon: lon

# timeresolution in minutes, if None: timeresolution equal to resolution of COSMO data
timeresolution: None #15.

#Number of pixels in lat lon direction to use for averaging
pixel_avg:
    lat: 1
    lon: 2

# latitude, longitude of locations (position of solar power plants) within the COSMO grid
stations_lat_lon:
    MS_01: [47.715877,10.314037]
    MS_02: [47.683233,10.319028]
    PV_04: [47.76683,10.40843]
    PV_11: [47.653161,10.496584]
    PV_12: [47.640997,10.387674]
    PV_15: [47.61811,10.49656]   
    PV_03: [47.76754,10.39832]
    PV_06: [47.75014,10.31668]
    PV_16: [47.61035,10.22710]
    PV_20: [47.54129,10.43964]
    PV_21: [47.53019,10.25957]
    PV_01: [47.79314,10.41914]
    PV_07: [47.74298,10.23326]
    PV_13: [47.64058,10.24982]
    PV_18: [47.58829,10.23160]
    PV_08: [47.71985,10.23064]
    PV_17: [47.59261,10.09873]
    PV_09: [47.71785,10.31660]
    PV_14: [47.63978,10.11741]
    PV_22: [47.46471,10.26521]
    PV_10: [47.66487,10.11355]
    PV_19: [47.54270,10.44595]
    PV_02: [47.76869,10.40038]
    PV_05: [47.76352,10.40331]
