# config file for PV forward model calibration

#Description of datasets for current simulation
description: [messkampagne_2018_clear_sky,messkampagne_2019_all_sky]

#Configuration of raw data
data_configfile: 
    mk_2018: config_data_2018_messkampagne.yaml #/home/james/MetPVNet/Code/pvcal/
    mk_2019: config_data_2019_messkampagne.yaml #/home/james/MetPVNet/Code/pvcal/    

#Configuration of DISORT RT simulation
rt_configfile: config_PVPYRCAL_RT_MetPVNet_messkampagne.yaml #/home/james/MetPVNet/Code/pvcal/

#Configuration of inversion and PV model
pv_configfile: 
    mk_2018: config_PYRCAL_inversion_2018_messkampagne.yaml #/home/james/MetPVNet/Code/pvcal/
    mk_2019: config_PYRCAL_inversion_2019_messkampagne.yaml #/home/james/MetPVNet/Code/pvcal/

#Plot style
plot_styles: 
    single_small: my_paper
    combo_small: my_paper_grid
    single_large: my_presi
    combo_large: my_presi_grid