# config file for data processing script

#Description of current simulation
description: messkampagne_2018_clear_sky

#Table with configuration information 
configtable: 20181121_MetPVNet_Anlagenuebersicht_v1.4_JB.xlsx

# Path definitions, i.e. where the data is stored
paths: 
    mainpath: /mnt/bigdata/share/00_Projects/1_MetPVNet/Messkampagne/00_Messdaten/00_Messdaten_Kampagne_2018/
    #AUEW data subfolders
    auew: 
        path: Leistungsmessung_AUEW
    #Egrid data subfolders
    egrid: 
        path: Leistungsmessung_egrid
    temp:
        path: PV-Modul_Temperatursensor
    wind:
        path: Windmessmast
    pmaxdoas:
        path: [PMAX-DOAS,general]
    #Folders to save plots
    plots: 
        main: MetPVNet/Data/Messkampagne/Plots
        pv: PV
        rad: Irrad
        temp: Temp
        combo: Combo    
    savedata:
        main: MetPVNet/Data/Messkampagne
        #Folder to save binary data
        binary: Pickled_Data
        #Folder to save CSV data
        csv: CSV_Data
    
#config for data processing
data_processing:
    auew:
        time_integral: 15
        units: minutes
    module_temp:
        MS_02:
            flag: True
            slope: 8.90263884259304e-05
            start_time: '2018-09-06 10:00:00' 
        PV_12:
            flag: True
            slope: 7.0862340896255e-05
            start_time: '2018-09-06 10:00:00'
        PV_11:
            flag: False
    substat_switch:
        PV_11:
            old_name: egrid
            new_name: egrid_1

#Time resolutions to use for resampling
time_resolution: [15S,1min,15min]

#Boolean
resample: True #False 

#Datatypes for import
data_types: [pv,irrad,temp,wind]
        
#stations to import, can be "all" or a list of station names, i.e. "MS_01", PV_05" etc
stations: MS_01 #PV_09 
#PVCAL: [PV_01,PV_03,PV_04,PV_06,PV_07,PV_08,PV_09,PV_10,PV_11,PV_12,PV_14,PV_15,PV_16,PV_18,PV_19,PV_21,PV_22] 
#PYRCAL [MS_01,MS_02,PV_01,PV_02,PV_03,PV_04,PV_06,PV_07,PV_08,PV_09,PV_10,PV_11,PV_12,PV_13,PV_14,PV_15,PV_16,PV_17,PV_18,PV_19,PV_20,PV_21,PV_22] 


# Plotting flags - turn plotting on and off
plot_flags:
    pv: False #True 
    irrad: False #True #False #True #False 
    temp: False #True #True
    combo_p_rad: False #True #False #True #False #True #False #True #True #False
    combo_p_temp: False #True #False #True
    
save_flag:
    raw: True #False #True #False #True #False #True #False #True
    resampled: True #False #True #False #True #False #True #False    
    
#Plot style
plot_styles: 
    single_small: my_paper
    combo_small: my_paper_grid
    single_large: my_presi
    combo_large: my_presi_grid
